
name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World!"
          echo "Done - bye!"
          
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run a script
        run: echo "challa srikanth"
        
  third-job:
    needs: [first-job, second-job]
    runs-on: ubuntu-latest
    steps:
    - name: output github context
      run: echo "${{tojson(github)}}"
